name: cube-creator
env_file:
  - .local.env
  - .env
services:
  core:
    type: node:custom
    command: npx nodemon -w packages -w apis --verbose --ext ts,ttl,js,trig --ignore **/*.test.ts --ignore **/*.spec-graphs.ts --exec node --inspect=0.0.0.0:45671 -r ts-node/register --inspect apis/core/index.ts
    ssl: true
    overrides:
      image: node:14
      ports:
        - "45671:45671"
      environment:
        TS_NODE_TRANSPILE_ONLY: "true"
        TS_NODE_PROJECT: apis/core/tsconfig.json
        # This should be kept in sync with api.Dockerfile
        DEBUG: creator*,hydra*,hydra-box*,labyrinth*,dimensions*
      depends_on:
        store:
          condition: service_healthy
    moreHttpPorts:
      - 45671
  ui:
    type: node:16
    command: (cd ui; yarn serve --public app.cube-creator.lndo.site --hostname 0.0.0.0 --port 80)
    ssl: true
    overrides:
      environment:
        NO_WEBSOCKET: "true"
  store:
    type: compose
    ssl: true
    build_as_root:
      - /opt/java-minimal/bin/keytool -importcert -trustcacerts -noprompt -storepass changeit -cacerts -file /usr/share/ca-certificates/lndo.site.pem -alias LandoCert
    services:
      image: ghcr.io/zazuko/fuseki-geosparql:v2.0.3
      command: /opt/fuseki/entrypoint.sh
      user: root
      environment:
        ADMIN_PASSWORD: password
        OTEL_SERVICE_NAME: store
        OTEL_TRACES_EXPORTER: jaeger
        OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14250
        OTEL_PROPAGATORS: tracecontext,jaeger
      volumes:
        - ./fuseki/config.ttl:/fuseki/config.ttl
      healthcheck:
        test: wget --no-verbose --tries=1 --spider http://localhost:3030/$$/ping || exit 1
        interval: 5s
        timeout: 3s
        retries: 10
      depends_on:
        - collector
  trifid:
    type: compose
    app_mount: false
    ssl: true
    services:
      image: zazuko/trifid
      user: root
      command: tini -- /app/server.js --config=/config-sparql.json --sparql-endpoint-url=http://admin:password@db.cube-creator.lndo.site/cube-creator
      environment:
        DEBUG: "trifid*"
  s3:
    type: compose
    ssl: true
    services:
      image: minio/minio:RELEASE.2020-12-03T05-49-24Z
      command: usr/bin/docker-entrypoint.sh server /data
      environment:
        MINIO_ACCESS_KEY: minio
        MINIO_SECRET_KEY: password
      volumes:
        - ./minio:/data/
  pipeline:
    type: node:custom
    command: npx nodemon -w packages -w cli --verbose --ext ts,ttl,js,trig --ignore **/*.spec.ts --ignore **/*.spec-graphs.ts --exec node --inspect=0.0.0.0:45681 -r ts-node/register --inspect cli/server.ts
    port: 80
    overrides:
      image: node:14
      environment:
        TS_NODE_TRANSPILE_ONLY: "true"
        NODE_TLS_REJECT_UNAUTHORIZED: 0
    moreHttpPorts:
      - 45681
  collector:
    type: compose
    scanner: false
    services:
      build:
        context: ./otel
        dockerfile: .Dockerfile
      command: /otel/otelcol --config=/collector.yaml
      ports:
        - 55681:55681
        - 8889:8889
      volumes:
        - ./otel/collector.yaml:/collector.yaml:ro
      depends_on:
        jaeger:
          condition: service_healthy
  jaeger:
    type: compose
    scanner: false
    services:
      image: jaegertracing/all-in-one:1.22
      command: /go/bin/all-in-one-linux --sampling.strategies-file=/etc/jaeger/sampling_strategies.json
      healthcheck:
        test: wget -nv -t1 --spider localhost:14269/ || exit 1
        interval: 5s
        timeout: 3s
        retries: 10
  prometheus:
    type: compose
    scanner: false
    services:
      image: prom/prometheus:v2.26.0
      command: /bin/prometheus --config.file=/prometheus.yaml --web.enable-lifecycle
      volumes:
        - ./otel/prometheus.yaml:/prometheus.yaml:ro

proxy:
  store:
    - db.cube-creator.lndo.site:3030
  trifid:
    - trifid.cube-creator.lndo.site:8080
  core:
    - cube-creator.lndo.site:45670
  ui:
    - app.cube-creator.lndo.site
  s3:
    - s3.cube-creator.lndo.site:9000
  pipeline:
    - pipeline.cube-creator.lndo.site
  collector:
    - otel.cube-creator.lndo.site:55681
  jaeger:
    - jaeger.cube-creator.lndo.site:16686
  prometheus:
    - prometheus.cube-creator.lndo.site:9090
