name: cube-creator
env_file:
  - .local.env
  - .env
services:
  core:
    type: node:custom
    command: yarn nodemon -w packages -w apis --verbose --ext ts,ttl,js,trig --ignore **/*.spec.ts --ignore **/*.spec-graphs.ts --exec node --inspect=0.0.0.0:45671 -r ts-node/register --inspect apis/core/index.ts
    port: 45670
    ssl: true
    overrides:
      image: node:14
      ports:
        - '45671:45671'
      environment:
        TS_NODE_PROJECT: apis/core/tsconfig.json
        DEBUG: creator*,hydra*,hydra-box*
    moreHttpPorts:
      - 45671
  ui:
    type: node:13
    command: (cd ui; yarn serve --public app.cube-creator.lndo.site)
    scanner: false
    ssl: true
  store:
    type: compose
    services:
      image: blankdots/jena-fuseki:fuseki3.13.1
      command: /docker-entrypoint.sh /jena-fuseki/start-fuseki.sh
      environment:
        ADMIN_PASSWORD: password
        ENABLE_DATA_WRITE: "true"
        ENABLE_UPDATE: "true"
        ENABLE_UPLOAD: "true"
      volumes:
        - ./fuseki/config.ttl:/data/fuseki/config/config.ttl
  dex:
    type: compose
    ssl: true
    services:
      image: quay.io/dexidp/dex:v2.24.0
      command: dex serve /config.yaml
      volumes:
        - dex-data:/data
        - ./dex/config.yaml:/config.yaml:ro
proxy:
  store:
    - db.cube-creator.lndo.site:3030
  core:
    - cube-creator.lndo.site:45670
  ui:
    - app.cube-creator.lndo.site:8080
  dex:
    - auth.cube-creator.lndo.site:5556
